name: telegram-ai-chatbot

services:
  api:
    image: django-backend:dev
    container_name: django-app
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/backend"
    env_file:
      - ./backend/.env

  frontend:
    image: vue-frontend:dev
    container_name: vue-app
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    ports:
      - "5173:5173"
    volumes:
      - "./frontend:/frontend"
      - "/frontend/node_modules"
    env_file:
      - ./frontend/.env