name: telegram-ai-chatbot

services:
  api:
    image: django-backend:prod
    container_name: django-app
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - DEBUG=False
      - CORS_ALLOWED_ORIGINS=http://localhost:8080
    depends_on:
      - postgresdb
    command: sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn djangoapp.wsgi:application --bind 0.0.0.0:8000"

  postgresdb:
    image: postgres:18
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    image: vue-frontend:prod
    container_name: vue-app
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"

volumes:
  postgres_data: